### ISSUE TITLE
鉴权部分和资源清单分离需求

### ISSUE THREAD

**Issue by oldthreefeng** [sealyun-market/marketctl#7]
原有的结构.  讲鉴权和 资源清单分离. 
```yaml
auth:
  domain: https://www.sealyun.com
  token: xxxxxx
market:
  body:
    spec:
      name: v1.19.10
      price: 50
      product:
        class: cloud_kernel
        productName: kubernetes
      url: http://www.baidu.com
    status:
      productVersionStatus: 2
  kind: productVersion
```

资源清单

```
market:
  body:
    spec:
      name: v1.19.10
      price: 50
      product:
        class: cloud_kernel
        productName: kubernetes
      url: http://www.baidu.com
    status:
      productVersionStatus: 2
  kind: productVersion
```

鉴权, 这部分可以在初始化的时候就注入,  然后以参数或者其他的方式注入到 create/delete/update当中.

```
auth:
  domain: https://www.sealyun.com
  token: xxxxxx
```
